name: Release Hotcakes Eslint

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    uses: crealgo/hotcakes-core/.github/workflows/semantic-release.yml@v1
    secrets: inherit
